name: YouTube Comment Bot Mekameleen

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: سحب ملفات الريبو
        uses: actions/checkout@v4

      - name: تجهيز بايثون
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تثبيت المكتبات
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: تشغيل البوت
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python bot.py
